apiVersion: apps/v1
kind: Deployment

metadata:
  name: dpy-home
  labels:
    app: hostname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostname
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
      - name: hname
        image: sheayun/hostname:latest
        ports:
          - containerPort: 80
